{% set name = "Omnipath" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 3821b9ba11957412ff9e4932eb6d0c17242939661468064ad1ce28ee3e27394f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - attrs >=20.2.0
    - docrep >=0.3.1
    - inflect >=4.1.0
    - packaging
    - pandas >=1.2.0
    - requests >=2.24.0
    - tqdm >=4.51.0
    - typing_extensions >=3.7.4.3
    - urllib3 >=1.26.0
    - wrapt >=1.12.0
  run_constrained:
    - networkx >=2.3.0

test:
  imports:
    - {{ name|lower }}
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/saezlab/omnipath
  license: MIT
  license_file: LICENSE
  summary: Python client for the OmniPath web service
  doc_url: https://omnipath.readthedocs.io
  dev_url: https://github.com/saezlab/omnipath

extra:
  recipe-maintainers:
    - michalk8
